import React from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Card, Pill, SectionTitle } from '../components/Ui';
import { useAppStore } from '../store/AppStore';
import { colors } from '../theme';
import { calculateProfit } from '../trading/engine';
import { percent, yen } from '../utils/format';

export function HomeScreen({ onPosition }: { onPosition: (symbol: string) => void }) {
  const { positions, settings, refreshing, refreshQuotes } = useAppStore();
  const marketValue = positions.reduce((sum, p) => sum + p.currentPrice * p.quantity, 0); const cost = positions.reduce((sum, p) => sum + p.averagePrice * p.quantity, 0); const profit = marketValue - cost;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refreshQuotes} tintColor={colors.primary}/>}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>PORTFOLIO</Text><Text style={styles.title}>おはようございます</Text></View><TouchableOpacity style={styles.iconButton} onPress={refreshQuotes}><Ionicons name="refresh" size={20} color={colors.primary}/></TouchableOpacity></View>
    <Card style={styles.hero}><View style={styles.heroTop}><Text style={styles.heroLabel}>総評価額</Text><Pill label={settings.globalTradingEnabled ? '自動売買 ON' : '自動売買 OFF'} tone={settings.globalTradingEnabled ? 'green' : 'gray'}/></View><Text style={styles.heroValue}>{yen(marketValue)}</Text><View style={styles.profitRow}><Ionicons name={profit >= 0 ? 'trending-up' : 'trending-down'} size={18} color={profit >= 0 ? colors.positive : colors.negative}/><Text style={[styles.profit, { color: profit >= 0 ? colors.positive : colors.negative }]}>{yen(profit)} ({percent(cost ? profit / cost * 100 : 0)})</Text><Text style={styles.today}> 評価損益</Text></View></Card>
    <View style={styles.metrics}><Card style={styles.metric}><Text style={styles.metricLabel}>保有銘柄</Text><Text style={styles.metricValue}>{positions.length}<Text style={styles.unit}> 銘柄</Text></Text></Card><Card style={styles.metric}><Text style={styles.metricLabel}>本日の損益</Text><Text style={[styles.metricValue, { color: colors.positive }]}>{yen(profit * 0.12)}</Text></Card></View>
    <SectionTitle title="保有銘柄" action="価格を更新" onPress={refreshQuotes}/>
    <Card style={styles.list}>{positions.slice(0, 3).map((p, i) => { const result = calculateProfit(p); return <TouchableOpacity key={p.symbol} style={[styles.row, i > 0 && styles.divider]} onPress={() => onPosition(p.symbol)}><View style={styles.logo}><Text style={styles.logoText}>{p.symbol.slice(0, 2)}</Text></View><View style={styles.stock}><Text style={styles.stockName} numberOfLines={1}>{p.name}</Text><Text style={styles.symbol}>{p.symbol} · {p.quantity}株</Text></View><View style={styles.price}><Text style={styles.stockPrice}>{yen(p.currentPrice)}</Text><Text style={{ color: result.profitPct >= 0 ? colors.positive : colors.negative, fontWeight: '700' }}>{percent(result.profitPct)}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></TouchableOpacity>})}</Card>
    <View style={styles.notice}><Ionicons name="shield-checkmark" size={20} color={colors.primary}/><Text style={styles.noticeText}>価格更新時のみ売買判定を実行します。アプリ終了中の常時監視には対応していません。</Text></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 110 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, eyebrow: { fontSize: 11, letterSpacing: 2, color: colors.primary, fontWeight: '800' }, title: { fontSize: 25, color: colors.ink, fontWeight: '800', marginTop: 4 }, iconButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, hero: { backgroundColor: colors.navy, borderColor: colors.navy, padding: 22 }, heroTop: { flexDirection: 'row', justifyContent: 'space-between' }, heroLabel: { color: '#B8C9CF', fontSize: 13 }, heroValue: { color: 'white', fontSize: 34, fontWeight: '800', marginTop: 12 }, profitRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 }, profit: { fontWeight: '800', marginLeft: 6 }, today: { color: '#B8C9CF', fontSize: 12 }, metrics: { flexDirection: 'row', gap: 12, marginTop: 12 }, metric: { flex: 1, padding: 16 }, metricLabel: { color: colors.muted, fontSize: 12 }, metricValue: { color: colors.ink, fontWeight: '800', fontSize: 19, marginTop: 8 }, unit: { fontSize: 12, fontWeight: '500' }, list: { paddingVertical: 2 }, row: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15 }, divider: { borderTopWidth: 1, borderTopColor: colors.border }, logo: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, logoText: { color: colors.primary, fontWeight: '800' }, stock: { flex: 1 }, stockName: { fontWeight: '700', color: colors.ink }, symbol: { color: colors.muted, fontSize: 12, marginTop: 4 }, price: { alignItems: 'flex-end', marginRight: 8, gap: 3 }, stockPrice: { color: colors.ink, fontWeight: '700' }, notice: { marginTop: 18, padding: 14, backgroundColor: colors.primarySoft, borderRadius: 14, flexDirection: 'row', gap: 10 }, noticeText: { flex: 1, color: colors.primary, fontSize: 12, lineHeight: 18 } });
